/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_app_jagles_video_GLVideoRender */

#ifndef _Included_com_app_jagles_video_GLVideoRender
#define _Included_com_app_jagles_video_GLVideoRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    InitManager
 * Signature: (FIILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_app_jagles_video_GLVideoRender_InitManager
        (JNIEnv *, jobject, jfloat, jint, jint, jstring);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    SetMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_SetMode
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    DrawRequest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_DrawRequest
        (JNIEnv *, jobject);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    StartAnimation
 * Signature: (J[FIIZIZIZI)J
 */
JNIEXPORT jlong JNICALL Java_com_app_jagles_video_GLVideoRender_StartAnimation
        (JNIEnv *, jobject, jlong, jfloatArray, jint, jint, jboolean, jint, jboolean, jint,
         jboolean, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    StopAnimation
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_StopAnimation
        (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    TextureAvaible
 * Signature: (JII[BIIIIJ)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_TextureAvaible
        (JNIEnv *, jobject, jlong, jint, jint, jbyteArray, jint, jint, jint, jint, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    OSDTextureAvaible
 * Signature: (JJIII)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_OSDTextureAvaible
        (JNIEnv *, jobject, jlong, jlong, jint, jint, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    DestroyManager
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_app_jagles_video_GLVideoRender_DestroyManager
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    DrawParametric
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_DrawParametric
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    TransformObject
 * Signature: (J[FIZI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_TransformObject
        (JNIEnv *, jobject, jlong, jfloatArray, jint, jboolean, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    Playfile
 * Signature: (JLjava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_Playfile
        (JNIEnv *, jobject, jlong, jstring, jboolean, jboolean);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    StopPlay
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_StopPlay
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    GetObjectPosition
 * Signature: (JIZI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_app_jagles_video_GLVideoRender_GetObjectPosition
        (JNIEnv *, jobject, jlong, jint, jboolean, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    SetSplit
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_SetSplit
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    SetScreenPage
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_SetScreenPage
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    SetSelected
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_SetSelected
        (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    SetSelectedByIndex
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_SetSelectedByIndex
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    GetPageIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_app_jagles_video_GLVideoRender_GetPageIndex
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    GetScreenCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_app_jagles_video_GLVideoRender_GetScreenCount
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    GetAllPage
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_app_jagles_video_GLVideoRender_GetAllPage
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    GetVideoIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_app_jagles_video_GLVideoRender_GetVideoIndex
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    GetMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_app_jagles_video_GLVideoRender_GetMode
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    SetSingVideo
 * Signature: (JIZ)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_SetSingVideo
        (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    GetSplitMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_app_jagles_video_GLVideoRender_GetSplitMode
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    ClearAnimation
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_ClearAnimation
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    GetScale
 * Signature: (JZI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_app_jagles_video_GLVideoRender_GetScale
        (JNIEnv *, jobject, jlong, jboolean, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    ResetPosition
 * Signature: (JZI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_ResetPosition
        (JNIEnv *, jobject, jlong, jboolean, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    GetVisibility
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_app_jagles_video_GLVideoRender_GetVisibility
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    DoStatus
 * Signature: (JLjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_DoStatus
        (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    ReSizeSplite
 * Signature: (JFII)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_ReSizeSplite
        (JNIEnv *, jobject, jlong, jfloat, jint, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    VRSensor
 * Signature: (J[F[FII)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_VRSensor
        (JNIEnv *, jobject, jlong, jfloatArray, jfloatArray, jint, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    LoadRecordStatuTexture
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_LoadRecordStatuTexture
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    SetWindowWidthHeight
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_SetWindowWidthHeight
        (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    DoTapOrMouseDown
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_DoTapOrMouseDown
        (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    DoTapOrMouseMove
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_DoTapOrMouseMove
        (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    DoTapOrMouseUp
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_DoTapOrMouseUp
        (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    DoTapOrMouseWheel
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_DoTapOrMouseWheel
        (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    DoDoubleTap
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_DoDoubleTap
        (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    UpdateAspect
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_UpdateAspect
        (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    SetAllPage
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_SetAllPage
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    CylinderWind
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_CylinderWind
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    CylinderUnwind
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_CylinderUnwind
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    HemisphereWind
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_HemisphereWind
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    HemisphereUnwind
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_HemisphereUnwind
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    TransformVertex
 * Signature: (JI[FZII)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_TransformVertex
        (JNIEnv *, jobject, jlong, jint, jfloatArray, jboolean, jint, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    EnableAudio
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_EnableAudio
        (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    OpenAudioPlaying
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_OpenAudioPlaying
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    PauseAudioPlaying
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_PauseAudioPlaying
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    DoDirectTextureFrameUpdata
 * Signature: (JJIIJI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_DoDirectTextureFrameUpdata
        (JNIEnv *, jobject, jlong, jlong, jint, jint, jlong, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    DoDirectTextureOSDFrameUpdata
 * Signature: (JJIIJI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_DoDirectTextureOSDFrameUpdata
        (JNIEnv *, jobject, jlong, jlong, jint, jint, jlong, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    PlayAudioData
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_PlayAudioData
        (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    EnableGrid
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_EnableGrid
        (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    ShowVideoLoading
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_ShowVideoLoading
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    HideVideoLoading
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_HideVideoLoading
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    StartMotionTracking
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_StartMotionTracking
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    StopMotionTracking
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_StopMotionTracking
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    AdjustActionExperience
 * Signature: (JIIF)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_AdjustActionExperience
        (JNIEnv *, jobject, jlong, jint, jint, jfloat);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    SetBorderColor
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_SetBorderColor
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    SetViewAngle
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_SetViewAngle
        (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    GetDualMode
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_app_jagles_video_GLVideoRender_GetDualMode
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    GetDualTexture
 * Signature: (J)I
 */
JNIEXPORT jboolean JNICALL Java_com_app_jagles_video_GLVideoRender_GetDualTexture
        (JNIEnv *, jobject, jlong);


JNIEXPORT void JNICALL
Java_com_app_jagles_video_GLVideoRender_CleanTexture(JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    SetHardwareTexture
 * Signature: (JIIIJ)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_SetHardwareTexture
        (JNIEnv *, jobject, jlong, jint, jint, jint, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    GetHaveCropParmeter
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_app_jagles_video_GLVideoRender_GetHaveCropParmeter
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    GetCropParameter
 * Signature: (JII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_app_jagles_video_GLVideoRender_GetCropParameter
        (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    SetCropInfo
 * Signature: (JJII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_app_jagles_video_GLVideoRender_SetCropInfo
        (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    SetFBOTexture
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_SetFBOTexture
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    RenderFBO
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_RenderFBO
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    GetIsHEVC
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_app_jagles_video_GLVideoRender_GetIsHEVC
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_app_jagles_video_GLVideoRender
 * Method:    CloseInfo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_video_GLVideoRender_CloseInfo
        (JNIEnv *, jobject, jlong);


#ifdef __cplusplus
}
#endif
#endif
