/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class com_app_jagles_smartlink_SmartLink */

#ifndef _Included_com_app_jagles_smartlink_SmartLink
#define _Included_com_app_jagles_smartlink_SmartLink

#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <syslog.h>
#include <stdbool.h>
#include <sys/times.h>
#include <sys/select.h>
#include <sys/ioctl.h>
#include <linux/if.h>
#include <sys/time.h>
#include <jni.h>


#define DEST_PORT 7000
#define SMART_LINK_TREAD_TRUE 1
#define SMART_LINK_TREAD_FALSE 0


/* smart_link init function, interface is the name of you wireless device
 * return -1 : There is no broadcard address in interface, please assign IP and netmask
 * return -2 : create the socket of send packet faid
 * return 0  : init success;
 * please must use nk_smart_link_quit() function to quik smart_link
 */
int nk_smart_link_init( char *interface );


/* The function of smart_link send packet , message is the message you want to sent to the client
 *
 * attention : The max length of message is 45, the message over 45 will be ignore,please noet that,ths;
 */
int nk_smart_link_send( char *message );


/* The function of quit smart_link
 * return 0  : normal quit
 * return -1 : fail to close socket
 */
int  nk_smart_link_quit();
/*
 * Class:     com_app_jagles_smartlink_SmartLink
 * Method:    smartLink
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_app_jagles_smartlink_SmartLink_smartLink
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_app_jagles_smartlink_SmartLink
 * Method:    quitsmartLink
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_smartlink_SmartLink_quitsmartLink
  (JNIEnv *, jobject);

/*
 * Class:     com_app_jagles_smartlink_SmartLink
 * Method:    smartLinkack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_app_jagles_smartlink_SmartLink_smartLinkack
  (JNIEnv *, jobject);

#endif
